[server]
fileWatcherType = "none"

[theme]
base = "light"
primaryColor = "#0969DA"
backgroundColor = "#F5F8FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#07133D"
borderColor = "#D3DFEC"
blueColor = "#0969DA"
greenColor = "#0A8F3D"
yellowColor = "#C96A00"
redColor = "#D20A16"
font = "sans serif"
baseFontSize = 15
baseFontWeight = 400
headingFontSizes = ["32px", "24px", "20px", "16px", "14px", "12px"]
headingFontWeights = [600, 600, 600, 600, 600, 600]
baseRadius = "large"
buttonRadius = "medium"
showWidgetBorder = true
linkUnderline = false

[theme.sidebar]
backgroundColor = "#0B3557"
secondaryBackgroundColor = "#124B77"
textColor = "#E7ECF5"
borderColor = "#235C85"
